  const exactOverrides = {
    'GetLedgerGroupList': 'Retrieves the list of ledger groups based on provided filters, used to classify accounts within the Chart of Accounts.',
    'LedgerGroupSummary': 'Retrieves summarized ledger group data based on provided filters for financial analysis and reporting.',
    'AutoCompleteLedgerList': 'Retrieves a filtered list of ledger accounts for auto-complete selection based on search criteria.',
    'GetAreaList': 'Retrieves the list of areas based on provided filters for classification and regional mapping.',
    'SaveDebtorRoute': 'Creates or updates debtor route information used for managing customer distribution and collection workflows.',
    'SaveDebtorType': 'Creates or updates debtor type classification used for categorizing customers in financial transactions.',
    'SaveLedger': 'Creates or updates ledger account records within the Chart of Accounts.',
    'SalesmanWisePartyList': 'Retrieves a list of parties grouped by salesman based on provided filters for sales and receivables analysis.',
    'GetPartyDuesBill': 'Retrieves party-wise outstanding dues and bill details based on provided filters for receivables tracking.',
    'CostCenterClosing': 'Retrieves cost center closing details based on provided parameters for financial period-end analysis.',
    'LedgerDetails': 'Retrieves detailed ledger account information based on provided filters or identifiers.',
    'GetLedgerVoucherDet': 'Retrieves ledger voucher details based on provided filters for transaction-level analysis.',
    'LedgerVoucher': 'Retrieves ledger voucher data based on provided filters for financial transaction tracking.',
    'PrintLedgerVoucherDet': 'Retrieves formatted ledger voucher details for printing based on provided filters.',
    'GetDebtorType': 'Retrieves debtor type details based on provided filters for customer classification.',
    'GetLedgerCategory': 'Retrieves ledger category details based on provided filters for account classification.',
    'GetLedgerChannel': 'Retrieves ledger channel details based on provided filters for business segmentation.',
    'GetAgentList': 'Retrieves the list of agents based on provided filters for operational and reporting purposes.',
    'GetAllVoucherModes': 'Retrieves available voucher modes based on provided filters for transaction processing.',
    'ProductVoucher': 'Retrieves product-related voucher details based on provided filters for inventory and financial tracking.',
    'VoucherEmail': 'Retrieves voucher details formatted for email delivery based on provided filters.',
    'PrintVoucher': 'Retrieves voucher details formatted for printing based on provided filters.',
    'GetPrintVoucher': 'Retrieves printable voucher data based on provided filters for document generation.',
    'SaveBG': 'Creates or updates bank guarantee records used for financial security and obligations tracking.',
    'GetPDCList': 'Retrieves post-dated cheque records based on provided filters for payment tracking.',
    'SavePDC': 'Creates or updates post-dated cheque records used in payment management.',
    'SaveLocalReceipt': 'Processes and retrieves local receipt details based on provided data for transaction confirmation.',
    'SaveReceipt': 'Creates or updates receipt records for recording incoming payments.',
    'SaveJournal': 'Creates or updates journal entries for recording financial transactions.',
    'GetCashBankBook': 'Retrieves cash and bank book details based on provided filters for financial tracking.',
    'GetBankReconciliation': 'Retrieves bank reconciliation data based on provided filters to match book and bank balances.',
    'DayBook': 'Retrieves day book entries based on provided filters for daily transaction tracking.',
    'GetCostClassList': 'Retrieves cost class records based on provided filters for cost allocation and analysis.',
    'SaveProductGroup': 'Creates or updates product group records used for categorizing inventory items.',
    'GetProductGroupSummaryAsList': 'Retrieves summarized product group data based on provided filters for reporting and analysis.',
    'GetProductGroupList': 'Retrieves product group records based on provided filters for classification purposes.',
    'SaveProductCategories': 'Creates or updates product category records for inventory classification.',
    'SaveProductCompany': 'Creates or updates product company (brand/manufacturer) records.',
    'GetCompetitorCompany': 'Retrieves competitor company details based on provided filters for market analysis.',
    'GetCompetitorProduct': 'Retrieves competitor product details based on provided filters for comparison and analysis.',
    'AutoCompleteProductList': 'Retrieves product suggestions based on search criteria for quick selection.',
    'SaveProduct': 'Creates or updates product records in the inventory system.',
    'ProductDetails': 'Retrieves detailed product information based on provided filters.',
    'ProductCurrentStatus': 'Retrieves current product status (availability/stock condition) based on provided filters.',
    'GetProductBrandList': 'Retrieves product brand records based on provided filters.',
    'GetProductForAbbreviatedInvoice': 'Retrieves product details formatted for abbreviated invoice generation.',
    'SaveUnit': 'Creates or updates unit of measurement records for products.',
    'PendingSalesOrderEmailToUserWithRangeValue': 'Retrieves pending sales order details based on filters for email notification within a specified range.',
    'PendingSalesOrderEmailToUser': 'Retrieves pending sales order details for email notification.',
    'BAEmailToUser': 'Retrieves business activity email data based on provided filters.',
    'PAEmailToAgent': 'Retrieves pending activity email data for agents based on provided filters.',
    'GetPendingSOSummary': 'Retrieves pending sales order summary based on provided filters.',
    'GetPendingPOSummary': 'Retrieves pending purchase order summary based on provided filters.',
    'GetCRLimitExpiredParty': 'Retrieves parties with expired credit limits based on provided filters.',
    'DailySalesEmailToAgentXLSX': 'Retrieves daily sales data formatted for Excel export and email to agents.',
    'SalesOrder': 'Creates or updates sales order records.',
    'GetPendingSalesOrderDet': 'Retrieves pending sales order details based on provided filters.',
    'GetPendingSalesOrder': 'Retrieves pending sales orders based on provided filters.',
    'AM_PendingSalesOrder': 'Retrieves area manager-wise pending sales orders based on provided filters.',
    'GetAllPaymentTerms': 'Retrieves payment terms based on provided filters.',
    'DailyOutStockBillEmailToUser': 'Retrieves daily outward stock bill details for email notification.',
    'SalesInvoiceDetailsMonthlyEmail': 'Retrieves monthly sales invoice details for email reporting.',
    'AbbsSalesInvoice': 'Creates or updates abbreviated sales invoice records.',
    'SalesInvoice': 'Creates or updates sales invoice records.',
    'AddSalesInvoice': 'Retrieves sales invoice details based on provided filters.',
    'SalesReturn': 'Creates or updates sales return records.',
    'SaveStockJournalOpening': 'Creates or updates stock journal opening records.',
    'Consumption': 'Creates or updates consumption records for inventory usage.',
    'PurchaseInvoice': 'Creates or updates purchase invoice records.',
    'GetSalesmanNameForGPS': 'Retrieves salesman details based on provided filters for GPS tracking and field operations.',
    'UpdateGeoLocation': 'Processes and updates geo-location data based on provided inputs for tracking purposes.',
    'LedgerGeoLocation': 'Creates or updates ledger geo-location mapping for location-based tracking.',
    'UpdateAppMissingLocation': 'Processes and updates missing application location data based on provided inputs.',
    'UpdateGPSLocation': 'Processes and updates GPS location data for tracking user movement.',
    'SaveManualGPS': 'Records manual GPS location entries based on provided inputs.',
    'GetGPSLog': 'Retrieves GPS log details based on provided filters for tracking history.',
    'GetSalesmanProfile': 'Retrieves salesman profile details based on provided filters.',
    'Agent GetProfile': 'Retrieves agent profile details based on provided filters.',
    'Agent GetPartyList': 'Retrieves a list of parties associated with an agent based on provided filters.',
    'GetSalesmanParentUserId': 'Retrieves parent user mapping details for a salesman based on provided filters.',
    'Exp_GetExpensesType': 'Retrieves expense types used for classification of expense entries.',
    'Exp_GetExpensesCategory': 'Retrieves expense categories based on provided filters.',
    'Exp_GetClaim': 'Retrieves expense claim details based on provided filters.',
    'Exp_Claim': 'Creates or updates expense claim records for reimbursement processing.',
    'Start Route Visit': 'Retrieves or initiates route visit details based on provided inputs for field tracking.',
    'WaitingFrom': 'Retrieves waiting status details based on provided inputs during field operations.',
    'SaveFromPlan': 'Processes route planning data based on provided inputs for scheduling visits.',
    'SaveRoutePlan': 'Creates or updates route plan records for field activity management.',
    'UpdateLedgerAddress': 'Creates or updates ledger/outlet address details for field mapping.',
    'NewCustomer': 'Creates or updates customer records during field operations.',
    'Get No Order': 'Processes and retrieves no-order details based on provided inputs.',
    'Update No Order Schedule': 'Creates or updates no-order scheduling records for planning purposes.',
    'SaveNoOrder': 'Creates or updates no-order records for sales tracking.',
    'SaveCDRParty': 'Creates or updates CDR (Call Detail Record) entries for field reporting.',
    'GetLeaveTypes': 'Retrieves available leave types based on provided filters.',
    'LeaveApproved': 'Retrieves approved leave details based on provided filters.',
    'AddLeaveRequest': 'Processes leave request submission based on provided inputs.',
    'LeaveRequest': 'Retrieves leave request details based on provided filters.',
    'GetLeaveBalance': 'Retrieves leave balance details based on provided filters.',
    'GetLeaveReqList': 'Retrieves leave request records based on provided filters.',
    'GetDailyAppAttendanceListForApproved': 'Retrieves approved daily attendance details based on provided filters.',
    'AttendanceAppealsListForApproved': 'Retrieves approved attendance appeal records based on provided filters.',
    'GetAttendanceInOutMode': 'Retrieves attendance in/out modes used in the system.',
    'GetDateWiseAttendance': 'Retrieves attendance details based on date filters.',
    'MyTeam': 'Retrieves team hierarchy details for the logged-in user.',
    'GetAppAttendanceLog': 'Retrieves application attendance logs based on provided filters.',
    'AppAttendance': 'Processes attendance marking based on provided inputs.',
    'PaySlip': 'Retrieves employee payslip details based on provided filters.',
    'AssetRequest': 'Processes or retrieves asset request details based on provided inputs.',
    'Agent GetTodaySales': 'Retrieves today\'s sales details for the agent based on provided filters.',
    'AgentDashboardSales': 'Retrieves dashboard sales data based on provided filters for analysis.',
    'IRD API Testing': 'Retrieves dashboard or reporting data for IRD integration testing.',
    'CancelTransaction': 'Processes transaction cancellation based on provided inputs.',
    'PostTransaction': 'Processes and posts financial transactions based on provided inputs.',
    'PostTransactionLog': 'Retrieves transaction posting logs based on provided filters.',
    'GetTransactionForEdit': 'Retrieves transaction details for editing based on provided filters.',
    'DelTransaction': 'Permanently deletes the specified transaction record.',
    'ExportCustomData': 'Retrieves custom data based on provided filters for export purposes.',
    'EmailCustomDataRDL': 'Retrieves and formats custom report data for email delivery.',
    'Email CustomData': 'Retrieves custom data formatted for email delivery.',
    'Print Custom Rid': 'Retrieves custom report data formatted for printing.',
    'PrintCustomData': 'Retrieves custom data formatted for printing.',
    'GetCustomAnno': 'Retrieves annotated custom data based on provided filters.',
    'GetCustomData': 'Retrieves custom data based on provided filters.',
    'GetMRSCustomData': 'Retrieves MRS-specific custom data based on provided filters.',
    'DynamicMIData': 'Retrieves dynamic management information data based on provided filters.',
    'CustomAction': 'Processes custom actions based on provided inputs.',
    'AddDynamicData Copy': 'Processes dynamic data creation based on provided inputs.',
    'StaticDynamicData': 'Retrieves static or dynamic configuration data.',
    'StaticValues': 'Retrieves predefined static values used across the system.',
    'GetCompanyList': 'Retrieves company records available in the system.',
    'GetGeneralConfig': 'Retrieves general configuration settings for the company.',
    'GetCompanyDetail': 'Retrieves company detail information.',
    'IsValidCompany': 'Validates whether the provided company code is valid.',
    'GetCompanyPeriodMonth': 'Retrieves company period/month configuration based on provided filters.',
    'UpdateUserPwd': 'Processes user password update based on provided inputs.',
    'IsValidUser': 'Retrieves and validates user details.',
    'BranchList': 'Retrieves branch records available in the system.',
    'SendSMS': 'Sends SMS/notification based on provided inputs.',
    'GetOneSignalSetup': 'Retrieves notification service configuration details.',
    'SendNotificationLog': 'Retrieves notification logs based on provided filters.',
    'SendNotificationGlobal': 'Sends global notifications based on provided inputs.',
    'SendNotification': 'Sends notifications based on provided inputs.',
    'DefaultRpt_Email': 'Retrieves default report data formatted for email delivery.',
    'GetVatRegister': 'Retrieves VAT register details based on provided filters.',
    'AccountSalesVatRegister': 'Retrieves sales VAT register details based on provided filters.',
    'GetStatutoryReport': 'Retrieves statutory report data based on provided filters.',
    'StockReport': 'Retrieves stock report details based on provided filters.',
    'GetNewVatRegister': 'Retrieves updated VAT register details based on provided filters.',
    'SendDlrReport': 'Retrieves dealer report data based on provided filters.',
    'GetGodownForStockDemand': 'Retrieves godown details based on provided filters for stock demand.',
    'SaveCompetitorSales': 'Creates or updates competitor sales records for market analysis.',
    'GetCompetitorSalesRpt': 'Retrieves competitor sales report data based on provided filters.',
    'SaveWeeklySalesRpt': 'Creates or updates weekly sales report records.',
    'GetWeeklySalesRpt': 'Retrieves weekly sales report data based on provided filters.',
    'SaveWeeklyProjection': 'Creates or updates weekly projection records.',
    'GetMonthlyProjection': 'Retrieves monthly projection data based on provided filters.',
    'GetPartyAeging Copy': 'Retrieves party ageing data from external/odata source.',
    'new token': 'Generates a new authentication token.',
    'Refresh Token': 'Refreshes the authentication token for continued access.',
    'GenFonepayQRRpt': 'Retrieves Fonepay QR transaction report based on provided filters.',
    'WebSocket Connect': 'Establishes a WebSocket connection for real-time communication.',
    'WebSocket SendMSG': 'Sends messages through WebSocket connection.',
  };
